export const CHAT_FETCH_MESSAGES_SUCCESSFULLY =
  "chat/CHAT_FETCH_MESSAGES_SUCCESSFULLY";
export const CHAT_FETCH_MESSAGES_FAILED = "chat/CHAT_FETCH_MESSAGES_FAILED";
export const CHAT_MESSAGES_ADDED = "chat/CHAT_MESSAGES_ADDED";
export const CHAT_MESSAGES_ADDED_ERROR = "chat/CHAT_MESSAGES_ADDED_ERROR";
